export const BESTPRODUCTS = [
  { id: 0, 
    image: 'assets/images/best-image-01.png',
    imageTag: 'assets/images/production-01.png',
    name: 'best product 1',
    desciption: 'How to create mobile-optimized', 
  },
  { id: 1, 
    image: 'assets/images/best-image-02.png',
    imageTag: 'assets/images/production-01.png',
    name: 'best product 2',
    desciption: 'How to create mobile-optimized', 
  },
  { id: 2, 
    image: 'assets/images/best-image-03.png',
    imageTag: 'assets/images/production-01.png',
    name: 'best product 3',
    desciption: 'How to create mobile-optimized', 
  },
]