export const PRODUCTS = [
  { id: 0, 
    image: 'assets/images/img-01.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 1, 
    image: 'assets/images/img-02.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 2, 
    image: 'assets/images/img-03.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 3, 
    image: 'assets/images/img-04.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 4, 
    image: 'assets/images/img-05.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 5, 
    image: 'assets/images/img-06.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 6, 
    image: 'assets/images/img-07.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 7, 
    image: 'assets/images/img-08.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 8, 
    image: 'assets/images/img-09.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 9, 
    image: 'assets/images/img-10.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 10, 
    image: 'assets/images/img-11.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 11, 
    image: 'assets/images/img-12.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 12, 
    image: 'assets/images/img-13.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 13, 
    image: 'assets/images/img-14.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 14, 
    image: 'assets/images/img-15.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 15, 
    image: 'assets/images/img-16.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 16, 
    image: 'assets/images/img-17.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 17, 
    image: 'assets/images/img-18.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 18, 
    image: 'assets/images/img-19.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 19, 
    image: 'assets/images/img-20.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 20, 
    image: 'assets/images/img-21.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 21, 
    image: 'assets/images/img-22.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 22, 
    image: 'assets/images/img-23.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 23, 
    image: 'assets/images/img-24.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
  { id: 24, 
    image: 'assets/images/img-25.png',
    name: '[What happen] How to create', 
    price: '2,500 won',
    rating: 236
  },
];